---
- name: check for confluent platform install...
  become: yes
  stat:
    path: '{{confluent_platform_install_dir}}'
  changed_when: false
  register: confluent_platform_binary
- when: not confluent_platform_binary.stat.exists
  block:
    - name: download tgz..
      become: yes
      become_user: root
      get_url:
        url: '{{confluent_platform_tgz_url}}'
        dest: /tmp/{{confluent_platform_tgz}}
        checksum: '{{confluent_platform_checksum}}'
        mode: 0644
    - name: unarchive...
      become: yes
      become_user: root
      unarchive:
        remote_src: yes
        src: /tmp/{{confluent_platform_tgz}}
        dest: '{{confluent_platform_parent_install_dir}}'
        creates: '{{confluent_platform_install_dir}}'
  always:
    - name: cleanup...
      become: yes
      become_user: root
      file:
        path: /tmp/{{confluent_platform_tgz}}
        state: absent

- name: link...
  become: yes
  become_user: root
  file:
    src: '{{confluent_platform_install_dir}}'
    dest: '{{confluent_platform_link_dir}}'
    state: link

- name: add confluent platform apps to the default login shell path...
  become: yes
  become_user: root
  with_items:
    - f: confluent.sh
      d: /etc/profile.d
  template:
    src: '{{item.f}}.j2'
    dest: '{{item.d}}/{{item.f}}'
    mode: '{{item.m|default("0644")}}'
